language: node_js

# Node 18 binaries require glibc >= 2.28
dist: focal

node_js:
  - 'stable'
  - '18'
  - '16'
  - '14'

cache:
  directories:
    - node_modules

# Set INIT_CWD for Husky due to Npm 7 not including it.
before_install:
  - export INIT_CWD="$(pwd)"

# Lint errors should trigger a failure.
before_script: npm run lint && npm run build

# Code coverage
script: npm run coveralls
